spring:
  application:
    name: config-service-local
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      ip: 192.168.0.13
      httpclient:
        connect-timeout: 3000
        response-timeout: 10s
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes: # routes 설정
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/api/**
          filters:
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}
